### ISSUE TITLE
Automatic down sampling

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#64]
```
from laserchicken import read_las
from laserchicken.keys import point
from laserchicken.spatial_selections import points_in_polygon_wkt
from laserchicken import write_ply

pc_in = read_las.read("D:/GitHub/eEcoLiDAR/eEcoLiDAR/testdata/AHN2.las")
pc_out = points_in_polygon_wkt(pc_in, "POLYGON(( 243590.0 572110.0, 243640.0 572160.0, 243700.0 572110.0, 243640.0 572060.0, 243590.0 572110.0 ))")

write_ply.write(pc_out, "D:/GitHub/komazsofi/myPhD_escience_analysis/test_data/testply.ply")
```
We got a downsampled point cloud as result within the polygon.

https://github.com/eEcoLiDAR/ecolidar_knowledgebase/blob/master/Figures/down1.PNG
https://github.com/eEcoLiDAR/ecolidar_knowledgebase/blob/master/Figures/down2.PNG

write_ply was tested to only read and export the original data into ply file that works well.

**Comment by komazsofi** [comment]
![](https://github.com/eEcoLiDAR/ecolidar_knowledgebase/blob/master/Figures/down1.PNG)

**Comment by cwmeijer** [comment]
Tried the following filtering instead (which includes every point and filters nothing out).
`
   pc_out = points_in_polygon_wkt(pc_in, "POLYGON(( 0.0 0.0, 1234567.0 0.0
       ...: , 1234567.0 1234567.0, 0.0 1234567.0, 0.0 0.0 ))")
`
The number of points in the cloud remains the same (according to cloud compare) but they are snapped to a 3d grid and projected onto each other because of that. This is probably because of precision loss somewhere during the spatial selection. Just reading the las file and writing as ply without any filtering works as expected (no snapping to grid).
